### ISSUE TITLE
Dont know if its just me, But none of these examples compile 

### ISSUE THREAD

**Issue by Rustie0125** [pschatzmann/arduino-flite#9]
Been trying to get this library working, but seems as if there are some issues around file names and includes that needs to be fixed before any of the libraries wants to compile.

**Comment by pschatzmann** [comment]
I can't help you, if you don't provide any meaningful context
- what sketch did you try
- what microcontroller
- what is the Arduino core version ?
- what were your error messages ?

I just made a test with the latest  ESP32 core version and could not reproduce any issue!

**Comment by Rustie0125** [comment]
I asked a simple question to see if it was a known issue. If it was then
nonpoint repeating all the details. Cleary it's not so I can provide the
details but you just closing stuff prematurely tells me the level of
support I can expect, so no worries.

**Comment by pschatzmann** [comment]
I don't see the point why you ask me to look up the open issues if you can do this yourself. My Arduino Github projects are done in my free time, so I expect that users don't push unnecessary work to me.

I am closing issues, so that I can keep track, if I still need to do something or not. In this case I did all I could do with the provided information.

Feel free to provide additional information if you still need some help.
